version: "3"

services:
  private-api:
    build: surfjudge-pyramid
    image: surfjudge-private
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./surfjudge-pyramid/app/surfjudge:/app/surfjudge:ro
      - ./surfjudge-pyramid/app/data:/app/data
    environment:
      WEBSOCKET_URL: $WEBSOCKET_URL
      ZEROMQ_PORT: 6545
      ZEROMQ_HOST: websockets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.surfjudge-private.rule=Host(`admin.${DOMAIN}`)"
      - "traefik.http.routers.surfjudge-private.tls.certresolver=le"
      - "traefik.http.routers.surfjudge-private.entrypoints=websecure"
    networks:
      - default

  public-api:
    build: surfjudge-actix
    image: surfjudge-public
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./surfjudge-vue-frontend/dist/static:/usr/src/app/static:ro
      - ./surfjudge-vue-frontend/dist/index.html:/usr/src/app/templates/index.html:ro
    environment:
      APP_DATABASE__URL: postgresql://postgres:surfjudge2000@postgres:5432/postgres
      APP_DATABASE__MAX_CONNECTIONS: 20
      APP_SERVER_ADDRESS: 0.0.0.0:8080
      APP_API__PUBLIC_PATH: /public
      APP_API__WEBSOCKET_URL: $WEBSOCKET_URL
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.surfjudge-public.rule=Host(`www.${DOMAIN}`) || Host(`${DOMAIN}`)"
      - "traefik.http.routers.surfjudge-public.tls.certresolver=le"
      - "traefik.http.routers.surfjudge-public.entrypoints=websecure"
      - "traefik.http.routers.surfjudge-public.middlewares=redirecttowww@docker"
      - "traefik.http.middlewares.redirecttowww.redirectregex.regex=^https://${DOMAIN}/(.*)"
      - "traefik.http.middlewares.redirecttowww.redirectregex.replacement=https://www.${DOMAIN}/$${1}"
    networks:
      - default

  judging-api:
    image: surfjudge-public
    restart: unless-stopped
    ports:
      - "8083:8080"
    volumes:
      - ./surfjudge-vue-frontend/dist/static:/usr/src/app/static:ro
      - ./surfjudge-vue-frontend/dist/index-judging.html:/usr/src/app/templates/index.html:ro
    environment:
      APP_DATABASE__URL: postgresql://postgres:surfjudge2000@postgres:5432/postgres
      APP_DATABASE__MAX_CONNECTIONS: 5
      APP_SERVER_ADDRESS: 0.0.0.0:8080
      APP_API__PUBLIC_PATH: /public
      APP_API__AUTH_PATH: /auth
      APP_API__JUDGING_PATH: /judging
      APP_API__WEBSOCKET_URL: $WEBSOCKET_URL
      APP_NOTIFICATIONS__ZMQ_SENDER_ADDRESS: websockets:6545
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.surfjudge-public.rule=Host(`judging.${DOMAIN}`))"
      - "traefik.http.routers.surfjudge-public.tls.certresolver=le"
      - "traefik.http.routers.surfjudge-public.entrypoints=websecure"
    networks:
      - default

  websockets:
    build: surfjudge-rust-websocket-server
    image: surfjudge-rust-websocket
    restart: unless-stopped
    ports:
      - 6544:6544
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.websockets.rule=Host(`${WEBSOCKET_URL}`)"
      - "traefik.http.routers.websockets.entrypoints=websecure"
      - "traefik.http.routers.websockets.tls.certresolver=le"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.websockets.middlewares=sslheader@docker"
      - "traefik.http.services.websockets.loadbalancer.server.port=6544"
    environment:
      RUST_LOG: INFO
      WEBSOCKETS_HOST: 0.0.0.0
      WEBSOCKETS_PORT: 6544
      ZMQ_PORT: 6545
    networks:
      - default


  # private-nginx:
  #   image: nginx:1.14.2
  #   restart: unless-stopped
  #   ports:
  #     - "8082:80"
  #   volumes:
  #     - ./surfjudge-pyramid/nginx/nginx_traefik.conf:/etc/nginx/nginx.conf:ro
  #     - ./surfjudge-pyramid/app/surfjudge/static:/surfjudge/static:ro
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.surfjudge-private.rule=Host(`admin.${DOMAIN}`)"
  #     - "traefik.http.routers.surfjudge-private.tls.certresolver=le"
  #     - "traefik.http.routers.surfjudge-private.entrypoints=websecure"
  #   networks:
  #     - default

  # public-nginx:
  #   image: nginx:1.14.2
  #   restart: unless-stopped
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ./surfjudge-actix/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./surfjudge-vue-frontend/dist/static:/www/data/static:ro
  #     - ./surfjudge-vue-frontend/dist/index.html:/www/data/index.html:ro
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.surfjudge-public.rule=Host(`www.${DOMAIN}`) || Host(`${DOMAIN}`)"
  #     - "traefik.http.routers.surfjudge-public.tls.certresolver=le"
  #     - "traefik.http.routers.surfjudge-public.entrypoints=websecure"
  #     - "traefik.http.routers.surfjudge-public.middlewares=redirecttowww@docker"
  #     - "traefik.http.middlewares.redirecttowww.redirectregex.regex=^https://${DOMAIN}/(.*)"
  #     - "traefik.http.middlewares.redirecttowww.redirectregex.replacement=https://www.${DOMAIN}/$${1}"
  #   networks:
  #     - default

  # judging-nginx:
  #   image: nginx:1.14.2
  #   restart: unless-stopped
  #   ports:
  #     - "8083:80"
  #   volumes:
  #     - ./surfjudge-actix/nginx/nginx-judging.conf:/etc/nginx/nginx.conf:ro
  #     - ./surfjudge-vue-frontend/dist/static:/www/data/static:ro
  #     - ./surfjudge-vue-frontend/dist/index-judging.html:/www/data/index.html:ro
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.surfjudge-public.rule=Host(`judging.${DOMAIN}`))"
  #     - "traefik.http.routers.surfjudge-public.tls.certresolver=le"
  #     - "traefik.http.routers.surfjudge-public.entrypoints=websecure"
  #     - "traefik.http.routers.surfjudge-public.middlewares=redirecttowww@docker"
  #   networks:
  #     - default


  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_PASSWORD: surfjudge2000
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    command:
      #- "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=dario.goetz@googlemail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    networks:
      - default

volumes:
  pgdata:
